# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SXPForum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SXPForum

  target 'SXPForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SXPForumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
