# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SXPForum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for SXPForum
   pod 'LeanCloud', '~> 11.0.0'
   pod 'Bugly'
   pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4'
   
  target 'SXPForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SXPForumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
